version: '3.4'

services:
  realestaterental:
    container_name: real-estate-rental
    image: realestaterental
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8084:8084

    network_mode: "host"
